variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  CONTAINER_TEST_IMAGE: registry.gitlab.com/dallastjames/divvylive/production:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/dallastjames/divvylive/production:latest

stages:
  - setup
  - tests
  - build
  - deploy

npm-install:
  image: node:10.6.0
  stage: setup
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules
    expire_in: 20 mins

lint:
  image: node:10.6.0
  stage: tests
  dependencies:
    - npm-install
  script:
    - npm run dallastjames:lint

test:
  image: amio/node-chrome
  stage: tests
  dependencies:
    - npm-install
  script:
    - npm run dallastjames:test

dallastjames-build-prod:
  image: docker:stable
  services:
    - docker:dind
  stage: build
  only:
    - master
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -f ./Dockerfile --tag $CONTAINER_IMAGE/dallastjames:$CI_BUILD_REF --tag $CONTAINER_IMAGE/dallastjames:latest .
    - docker push $CONTAINER_IMAGE/dallastjames:$CI_BUILD_REF
    - docker push $CONTAINER_IMAGE/dallastjames:latest

dallastjames-deploy:
  stage: deploy
  dependencies:
    - dallastjames-build-prod
  only:
    - master
  environment:
    name: production
    url: https://dallastjames.com
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan 35.230.87.53 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no -tt deploy@35.230.87.53 << EOF
    - docker pull $CONTAINER_IMAGE/dallastjames:latest
    - docker container stop dallastjames
    - docker container rm dallastjames
    - docker run -dit -p 5001:5001 --name=dallastjames --restart=unless-stopped $CONTAINER_IMAGE/dallastjames:latest
    - exit
